apiVersion: v1
kind: Secret
metadata: { name: ahla-auth, namespace: ahla-system }
type: Opaque
stringData:
  NEXTAUTH_SECRET: "{{ .Values.global.auth.nextAuthSecret }}"
  AUTH_KEYCLOAK_CLIENT_SECRET: "{{ .Values.global.auth.clientSecret }}"
