
events {}
http {
  server {
    listen 80;
    server_name _;
    add_header Content-Security-Policy "default-src 'self' 'unsafe-inline' data: blob:; connect-src 'self' ws: wss:; img-src 'self' data: blob;";
    location /mail/     { proxy_pass http://mail-web:3200/; }
    location /api/mail/ { proxy_pass http://mail-api:8300/; }
  }
}
