server {
  listen 80;
  server_name mta-sts.ahla.com;
  location /.well-known/acme-challenge/ {
    root /var/www/acme;
  }
  location /.well-known/mta-sts.txt {
    default_type text/plain;
    root /usr/share/nginx/html;
  }
}
server {
  listen 443 ssl;
  server_name mta-sts.ahla.com;
  ssl_certificate /etc/letsencrypt/live/mta-sts.ahla.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/mta-sts.ahla.com/privkey.pem;
  location /.well-known/mta-sts.txt {
    default_type text/plain;
    root /usr/share/nginx/html;
  }
}
