# TLS/SSL production-ish config
tls-listening-port=5349
lt-cred-mech
user=ahla:change-me-please
realm=ahla.turn
cert=/etc/letsencrypt/live/turn.your.domain.com/fullchain.pem
pkey=/etc/letsencrypt/live/turn.your.domain.com/privkey.pem
no-sslv3
no-tlsv1
min-port=49152
max-port=49999
fingerprint
stale-nonce=600
verbose
