apiVersion: v1
kind: Service
metadata:
  name: { include "ahla-diarization-service.fullname" . }
  labels:
{ include "ahla-diarization-service.labels" . | indent 4 }
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: { include "ahla-diarization-service.name" . }
    app.kubernetes.io/instance: { .Release.Name }
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.service.port }}
