apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ahla-chat-api.fullname" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ahla-chat-api.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
