
CREATE USER repl_user REPLICATION LOGIN ENCRYPTED PASSWORD 'repl_pass';
CREATE USER app_user WITH ENCRYPTED PASSWORD 'app_pass';
CREATE DATABASE ahla;
GRANT ALL PRIVILEGES ON DATABASE ahla TO app_user;
