apiVersion: v1
kind: Service
metadata:
  name: {{ include "ahla-web-app.fullname" . }}
  labels:
{{ include "ahla-web-app.labels" . | indent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "ahla-web-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.service.port }}
