apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: { include "ahla-translate-service.fullname" . }
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: { include "ahla-translate-service.name" . }
      app.kubernetes.io/instance: { .Release.Name }
