apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ahla-root
  namespace: argocd
spec:
  project: ahla
  source:
    repoURL: https://github.com/ahla/infra.git
    targetRevision: main
    path: argocd
    helm:
      parameters:
        - name: env
          value: "staging"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
